(()=>{'use strict';
const COLORS=['#5a4ff3','#e68a3c','#27a17c','#cf5b62','#4b7bd8'];
const TYPES={stock:'Stock',flow:'Flux',variable:'Variable',parameter:'Paramètre'};
const S={view:'model',model:null,selected:null,connect:false,connectSource:null,drag:null,last:null,scenario:'baseline'};
const $=id=>document.getElementById(id); const E={};
document.addEventListener('DOMContentLoaded',init);
function init(){['canvas','canvasWrap','edges','canvasEmpty','inspectorEmpty','inspectorContent','modelTitle','modelStats','connectBtn','toast','horizon','dt','timeUnit','kpis','chart','chartMetric','results','scenarioTabs','scenarioEditor','scenarioMetric','scenarioChart','loops','behaviour','quality','welcome'].forEach(x=>E[x]=$(x));bind();S.model=load()||example();normalize();renderAll();if(!localStorage.getItem('dc_onboarded'))E.welcome.classList.remove('hidden')}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addNode(b.dataset.add));$('connectBtn').onclick=()=>{S.connect=!S.connect;S.connectSource=null;renderModel();toast(S.connect?'Clique sur deux éléments à relier':'Mode lien désactivé')};$('runBtn').onclick=$('runBtn2').onclick=()=>{run();switchView('simulate')};$('saveBtn').onclick=()=>{save();toast('Sauvegardé')};$('newBtn').onclick=()=>{S.model=blank();S.selected=null;S.last=null;save();renderAll()};$('exampleBtn').onclick=()=>{S.model=example();S.selected=null;S.last=null;save();renderAll()};$('exportBtn').onclick=exportModel;$('addScenario').onclick=addScenario;$('scenarioMetric').onchange=renderScenarioChart;$('chartMetric').onchange=renderChart;$('startExample').onclick=()=>closeWelcome(false);$('startBlank').onclick=()=>closeWelcome(true);$('helpBtn').onclick=()=>E.welcome.classList.remove('hidden');['horizon','dt','timeUnit'].forEach(id=>$(id).onchange=()=>{S.model.simulation={horizon:+E.horizon.value||36,dt:+E.dt.value||1,unit:E.timeUnit.value||'mois'};save()});document.addEventListener('pointermove',moveDrag);document.addEventListener('pointerup',endDrag);window.addEventListener('resize',renderEdges);document.addEventListener('keydown',e=>{if(e.key==='Escape'){S.connect=false;S.connectSource=null;S.selected=null;renderAll()}if((e.key==='Delete'||e.key==='Backspace')&&S.selected&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))removeSelected()})}
function closeWelcome(blankStart){localStorage.setItem('dc_onboarded','1');E.welcome.classList.add('hidden');if(blankStart){S.model=blank();S.selected=null;save();renderAll()}}
function blank(){return{version:2,name:'Nouveau modèle',simulation:{horizon:36,dt:1,unit:'mois'},nodes:[],edges:[],scenarios:[{id:'baseline',name:'Baseline',color:COLORS[0],overrides:{}}]}}
function example(){return{version:2,name:'Adoption d’un produit',simulation:{horizon:36,dt:1,unit:'mois'},nodes:[{id:'potential',type:'stock',name:'Clients potentiels',symbol:'potential',x:85,y:130,initial:10000,unit:'clients'},{id:'acq',type:'flow',name:'Acquisition',symbol:'acquisition',x:340,y:150,formula:'potential * adoption_rate',from:'potential',to:'active',unit:'clients/mois'},{id:'active',type:'stock',name:'Clients actifs',symbol:'active',x:595,y:130,initial:500,unit:'clients'},{id:'churn',type:'flow',name:'Churn',symbol:'churn',x:835,y:150,formula:'active * churn_rate',from:'active',to:null,unit:'clients/mois'},{id:'adopt',type:'parameter',name:'Taux d’adoption',symbol:'adoption_rate',x:245,y:340,value:.018,min:.002,max:.05,step:.001,unit:'/mois'},{id:'churnr',type:'parameter',name:'Taux de churn',symbol:'churn_rate',x:705,y:340,value:.012,min:.001,max:.04,step:.001,unit:'/mois'},{id:'wom',type:'variable',name:'Bouche-à-oreille',symbol:'word_of_mouth',x:470,y:385,formula:'active / 1000',unit:'indice'}],edges:[{id:'e1',from:'potential',to:'acq',polarity:'+'},{id:'e2',from:'adopt',to:'acq',polarity:'+'},{id:'e3',from:'acq',to:'active',polarity:'+'},{id:'e4',from:'active',to:'churn',polarity:'+'},{id:'e5',from:'churnr',to:'churn',polarity:'+'},{id:'e6',from:'churn',to:'active',polarity:'-'},{id:'e7',from:'active',to:'wom',polarity:'+'},{id:'e8',from:'wom',to:'adopt',polarity:'+'}],scenarios:[{id:'baseline',name:'Baseline',color:COLORS[0],overrides:{}},{id:'growth',name:'Croissance forte',color:COLORS[1],overrides:{adoption_rate:.03}},{id:'retention',name:'Meilleure rétention',color:COLORS[2],overrides:{churn_rate:.006}}]}}
function normalize(){let m=S.model;m.nodes||=[];m.edges||=[];m.scenarios||=[];m.simulation||={horizon:36,dt:1,unit:'mois'};m.nodes.forEach((n,i)=>{n.id||=uid('n');n.symbol||=unique(slug(n.name||'element'),n.id);n.x=+n.x||100+i*20;n.y=+n.y||100+i*20;if(n.type==='stock')n.initial=+n.initial||0;if(n.type==='parameter'){n.value=+n.value||0;n.min=Number.isFinite(+n.min)?+n.min:0;n.max=Number.isFinite(+n.max)?+n.max:10;n.step=+n.step||.1}if(n.type==='flow'||n.type==='variable')n.formula||='0'})}
function renderAll(){renderNav();renderModel();renderInspector();renderSim();renderScenarios();renderInsights();E.horizon.value=S.model.simulation.horizon;E.dt.value=S.model.simulation.dt;E.timeUnit.value=S.model.simulation.unit}
function renderNav(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===S.view));['model','simulate','scenarios','insights'].forEach(v=>$(v+'View').classList.toggle('active',v===S.view))}
function switchView(v){S.view=v;renderNav();if(v==='simulate')renderSim();if(v==='scenarios')renderScenarios();if(v==='insights')renderInsights()}
function addNode(type){const n={id:uid('n'),type,x:Math.max(40,E.canvasWrap.clientWidth/2-80+Math.random()*40),y:160+Math.random()*160,unit:''};if(type==='stock')Object.assign(n,{name:'Nouveau stock',symbol:unique('stock'),initial:100});if(type==='flow')Object.assign(n,{name:'Nouveau flux',symbol:unique('flow'),formula:'0',from:null,to:null});if(type==='variable')Object.assign(n,{name:'Nouvelle variable',symbol:unique('variable'),formula:'0'});if(type==='parameter')Object.assign(n,{name:'Nouveau paramètre',symbol:unique('parameter'),value:1,min:0,max:10,step:.1});S.model.nodes.push(n);S.selected={kind:'node',id:n.id};save();renderAll()}
function renderModel(){E.canvas.innerHTML='';E.canvasEmpty.classList.toggle('hidden',S.model.nodes.length>0);E.modelTitle.textContent=S.model.name;E.modelStats.textContent=`${S.model.nodes.length} éléments · ${S.model.edges.length} liens`;E.connectBtn.style.background=S.connect?'#edeaff':'';S.model.nodes.forEach(n=>{const d=document.createElement('div');d.className=`node ${n.type}${S.selected?.kind==='node'&&S.selected.id===n.id?' selected':''}${S.connectSource===n.id?' connect-source':''}`;d.dataset.id=n.id;d.style.left=n.x+'px';d.style.top=n.y+'px';d.innerHTML=`<div class="node-type">${TYPES[n.type]}</div><div class="node-name">${esc(n.name)}</div><div class="node-meta">${esc(meta(n))}</div>`;d.onpointerdown=e=>startDrag(e,n.id);d.onclick=e=>clickNode(e,n.id);E.canvas.appendChild(d)});requestAnimationFrame(renderEdges)}
function meta(n){if(n.type==='stock')return `${fmt(n.initial)} ${n.unit||''}`;if(n.type==='parameter')return `${fmt(n.value)} ${n.unit||''}`;return n.formula||'0'}
function startDrag(e,id){if(S.connect)return;const n=node(id);S.drag={id,sx:e.clientX,sy:e.clientY,x:n.x,y:n.y,moved:false}}
function moveDrag(e){if(!S.drag)return;const n=node(S.drag.id),dx=e.clientX-S.drag.sx,dy=e.clientY-S.drag.sy;S.drag.moved=Math.abs(dx)+Math.abs(dy)>3;n.x=Math.max(8,S.drag.x+dx);n.y=Math.max(8,S.drag.y+dy);const el=E.canvas.querySelector(`[data-id="${n.id}"]`);if(el){el.style.left=n.x+'px';el.style.top=n.y+'px'}renderEdges()}
function endDrag(){if(S.drag?.moved)save();S.drag=null}
function clickNode(e,id){if(S.drag?.moved)return;if(S.connect){if(!S.connectSource){S.connectSource=id;renderModel();return}if(S.connectSource!==id){S.model.edges.push({id:uid('e'),from:S.connectSource,to:id,polarity:'+'});S.connectSource=null;save();renderAll()}return}S.selected={kind:'node',id};renderModel();renderInspector()}
function renderEdges(){const wr=E.canvasWrap.getBoundingClientRect(),els={};E.canvas.querySelectorAll('.node').forEach(x=>els[x.dataset.id]=x);let out='<defs><marker id="arr" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#697386"/></marker></defs>';S.model.edges.forEach(ed=>{let a=els[ed.from],b=els[ed.to];if(!a||!b)return;let ra=a.getBoundingClientRect(),rb=b.getBoundingClientRect(),x1=ra.left-wr.left+ra.width/2,y1=ra.top-wr.top+ra.height/2,x2=rb.left-wr.left+rb.width/2,y2=rb.top-wr.top+rb.height/2,dx=Math.max(50,Math.abs(x2-x1)*.42),p=`M${x1},${y1} C${x1+(x2>=x1?dx:-dx)},${y1} ${x2-(x2>=x1?dx:-dx)},${y2} ${x2},${y2}`,mx=(x1+x2)/2,my=(y1+y2)/2;out+=`<path d="${p}" fill="none" stroke="#697386" stroke-width="1.6" marker-end="url(#arr)"/><circle cx="${mx}" cy="${my}" r="10" fill="#fff" stroke="#dde2eb"/><text x="${mx}" y="${my+4}" text-anchor="middle" font-size="11" font-weight="800" fill="${ed.polarity==='-'?'#cf5b62':'#445'}">${ed.polarity||'+'}</text>`});E.edges.innerHTML=out}
function renderInspector(){if(S.selected?.kind!=='node'){E.inspectorEmpty.classList.remove('hidden');E.inspectorContent.classList.add('hidden');return}let n=node(S.selected.id);if(!n)return;E.inspectorEmpty.classList.add('hidden');E.inspectorContent.classList.remove('hidden');let html=`<span class="eyebrow">${TYPES[n.type]}</span><h3>${esc(n.name)}</h3>${field('Nom',`<input data-prop="name" value="${attr(n.name)}">`)}${field('Symbole',`<input data-prop="symbol" value="${attr(n.symbol)}">`)}${field('Unité',`<input data-prop="unit" value="${attr(n.unit||'')}">`)}`;if(n.type==='stock')html+=field('Valeur initiale',`<input type="number" data-prop="initial" value="${n.initial}">`);if(n.type==='parameter')html+=field('Valeur',`<input type="number" step="any" data-prop="value" value="${n.value}">`)+`<div class="form-row">${field('Min',`<input type="number" step="any" data-prop="min" value="${n.min}">`)}${field('Max',`<input type="number" step="any" data-prop="max" value="${n.max}">`)}</div>`+field('Pas',`<input type="number" step="any" data-prop="step" value="${n.step}">`);if(n.type==='flow'||n.type==='variable')html+=field('Formule',`<textarea rows="4" data-prop="formula">${esc(n.formula)}</textarea>`);if(n.type==='flow'){let opts=`<option value="">— extérieur —</option>`+S.model.nodes.filter(x=>x.type==='stock').map(x=>`<option value="${x.id}" ${n.from===x.id?'selected':''}>${esc(x.name)}</option>`).join('');html+=field('Stock source',`<select data-prop="from">${opts}</select>`);let opts2=`<option value="">— extérieur —</option>`+S.model.nodes.filter(x=>x.type==='stock').map(x=>`<option value="${x.id}" ${n.to===x.id?'selected':''}>${esc(x.name)}</option>`).join('');html+=field('Stock destination',`<select data-prop="to">${opts2}</select>`)}html+=`<button id="deleteNode" class="btn wide danger">Supprimer cet élément</button>`;E.inspectorContent.innerHTML=html;E.inspectorContent.querySelectorAll('[data-prop]').forEach(inp=>inp.onchange=()=>{let p=inp.dataset.prop,v=inp.value;if(['initial','value','min','max','step'].includes(p))v=+v||0;n[p]=v;if(p==='name'&&!n.symbol)n.symbol=unique(slug(v),n.id);save();renderModel();renderInspector()});$('deleteNode').onclick=removeSelected}
function field(l,c){return `<div class="form-group"><label>${l}</label>${c}</div>`}
function removeSelected(){if(S.selected?.kind!=='node')return;let id=S.selected.id;S.model.nodes=S.model.nodes.filter(n=>n.id!==id);S.model.edges=S.model.edges.filter(e=>e.from!==id&&e.to!==id);S.selected=null;save();renderAll()}
function run(overrides={}){try{S.last=simulate(overrides);renderSim();toast('Simulation terminée')}catch(e){toast('Erreur de formule : '+e.message)}}
function simulate(overrides={}){const cfg=S.model.simulation,steps=Math.ceil(cfg.horizon/cfg.dt),stocks=S.model.nodes.filter(n=>n.type==='stock'),flows=S.model.nodes.filter(n=>n.type==='flow'),params=S.model.nodes.filter(n=>n.type==='parameter'),vars=S.model.nodes.filter(n=>n.type==='variable'),state={};stocks.forEach(n=>state[n.symbol]=+n.initial||0);const series={time:[]};S.model.nodes.forEach(n=>series[n.symbol]=[]);for(let i=0;i<=steps;i++){const t=i*cfg.dt,ctx={...state,time:t};params.forEach(n=>ctx[n.symbol]=(n.symbol in overrides)?overrides[n.symbol]:n.value);vars.forEach(n=>ctx[n.symbol]=evalExpr(n.formula,ctx));flows.forEach(n=>ctx[n.symbol]=Math.max(0,evalExpr(n.formula,ctx)));series.time.push(t);S.model.nodes.forEach(n=>series[n.symbol].push(ctx[n.symbol]??state[n.symbol]??0));if(i===steps)break;const delta={};stocks.forEach(n=>delta[n.symbol]=0);flows.forEach(f=>{const v=ctx[f.symbol]||0;if(f.from){let s=node(f.from);if(s)delta[s.symbol]-=v*cfg.dt}if(f.to){let s=node(f.to);if(s)delta[s.symbol]+=v*cfg.dt}});stocks.forEach(n=>state[n.symbol]=Math.max(0,state[n.symbol]+delta[n.symbol]))}return{series,final:Object.fromEntries(S.model.nodes.map(n=>[n.symbol,series[n.symbol].at(-1)]))}}
function evalExpr(expr,ctx){const names=Object.keys(ctx),vals=Object.values(ctx);return Number(Function(...names,`"use strict"; return (${expr||0});`)(...vals))||0}
function renderSim(){let stocks=S.model.nodes.filter(n=>n.type==='stock');E.chartMetric.innerHTML=stocks.map(n=>`<option value="${n.symbol}">${esc(n.name)}</option>`).join('');if(!S.last){S.last=simulate({})}let finals=S.last.final;E.kpis.innerHTML=stocks.slice(0,4).map(n=>`<div class="kpi"><small>${esc(n.name)}</small><strong>${fmt(finals[n.symbol])}</strong><small>${esc(n.unit||'')}</small></div>`).join('');E.results.innerHTML=S.model.nodes.map(n=>`<div class="result-item"><small>${TYPES[n.type]} · ${esc(n.symbol)}</small><strong>${fmt(finals[n.symbol])} ${esc(n.unit||'')}</strong></div>`).join('');renderChart()}
function renderChart(){if(!S.last)return;let sym=E.chartMetric.value||S.model.nodes.find(n=>n.type==='stock')?.symbol;if(!sym)return;drawLines(E.chart,[{name:sym,color:COLORS[0],x:S.last.series.time,y:S.last.series[sym]}])}
function addScenario(){let id=uid('s');S.model.scenarios.push({id,name:'Nouveau scénario',color:COLORS[S.model.scenarios.length%COLORS.length],overrides:{}});S.scenario=id;save();renderScenarios()}
function renderScenarios(){if(!S.model.scenarios.length)S.model.scenarios=[{id:'baseline',name:'Baseline',color:COLORS[0],overrides:{}}];if(!S.model.scenarios.some(s=>s.id===S.scenario))S.scenario=S.model.scenarios[0].id;E.scenarioTabs.innerHTML=S.model.scenarios.map(s=>`<button class="scenario-tab ${s.id===S.scenario?'active':''}" data-sid="${s.id}"><strong>${esc(s.name)}</strong><small>${Object.keys(s.overrides).length||'Aucune'} hypothèse${Object.keys(s.overrides).length>1?'s':''}</small></button>`).join('');E.scenarioTabs.querySelectorAll('[data-sid]').forEach(b=>b.onclick=()=>{S.scenario=b.dataset.sid;renderScenarios()});let sc=S.model.scenarios.find(s=>s.id===S.scenario),params=S.model.nodes.filter(n=>n.type==='parameter');E.scenarioEditor.innerHTML=`<div class="card-head"><div><h3>${esc(sc.name)}</h3><p>Modifie les paramètres de ce scénario</p></div></div>${params.length?params.map(p=>{let v=(p.symbol in sc.overrides)?sc.overrides[p.symbol]:p.value;return `<div class="slider-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.unit||'')}</small></div><input type="range" min="${p.min}" max="${p.max}" step="${p.step}" value="${v}" data-range="${p.symbol}"><input type="number" step="${p.step}" value="${v}" data-num="${p.symbol}"></div>`}).join(''):'<p>Aucun paramètre ajustable.</p>'}`;E.scenarioEditor.querySelectorAll('[data-range]').forEach(r=>r.oninput=()=>updateScenario(r.dataset.range,+r.value));E.scenarioEditor.querySelectorAll('[data-num]').forEach(r=>r.onchange=()=>updateScenario(r.dataset.num,+r.value));let stocks=S.model.nodes.filter(n=>n.type==='stock');E.scenarioMetric.innerHTML=stocks.map(n=>`<option value="${n.symbol}">${esc(n.name)}</option>`).join('');renderScenarioChart()}
function updateScenario(sym,v){let sc=S.model.scenarios.find(s=>s.id===S.scenario),base=S.model.nodes.find(n=>n.symbol===sym)?.value;if(Math.abs(v-base)<1e-12)delete sc.overrides[sym];else sc.overrides[sym]=v;save();renderScenarios()}
function renderScenarioChart(){let sym=E.scenarioMetric.value||S.model.nodes.find(n=>n.type==='stock')?.symbol;if(!sym)return;let lines=S.model.scenarios.map(sc=>{let sim=simulate(sc.overrides);return{name:sc.name,color:sc.color,x:sim.series.time,y:sim.series[sym]}});drawLines(E.scenarioChart,lines)}
function drawLines(el,lines){let W=900,H=320,p=42,all=lines.flatMap(l=>l.y),min=Math.min(...all),max=Math.max(...all);if(max===min)max=min+1;let xmax=Math.max(...lines[0].x);const X=x=>p+(x/xmax)*(W-p*2),Y=y=>H-p-((y-min)/(max-min))*(H-p*2);let s=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}" stroke="#dfe4ec"/><line x1="${p}" y1="${p}" x2="${p}" y2="${H-p}" stroke="#dfe4ec"/>`;for(let k=0;k<5;k++){let y=p+k*(H-p*2)/4,val=max-k*(max-min)/4;s+=`<text x="6" y="${y+4}" font-size="11" fill="#8a93a6">${fmt(val)}</text><line x1="${p}" y1="${y}" x2="${W-p}" y2="${y}" stroke="#eef1f6"/>`}lines.forEach(l=>{let pts=l.x.map((x,i)=>`${X(x)},${Y(l.y[i])}`).join(' ');s+=`<polyline fill="none" stroke="${l.color}" stroke-width="3" points="${pts}"/>`});s+='</svg><div style="display:flex;gap:16px;justify-content:center;font-size:12px">'+lines.map(l=>`<span><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${l.color};margin-right:5px"></i>${esc(l.name)}</span>`).join('')+'</div>';el.innerHTML=s}
function renderInsights(){let loops=findLoops();E.loops.innerHTML=loops.length?loops.slice(0,6).map(l=>`<div class="insight"><strong>${l.sign>0?'↻ Boucle de renforcement':'↺ Boucle d’équilibrage'}</strong><small>${l.nodes.map(id=>node(id)?.name).filter(Boolean).join(' → ')}</small></div>`).join(''):'<div class="insight"><strong>Aucune boucle détectée</strong><small>Ajoute des liens causaux pour identifier les rétroactions.</small></div>';if(!S.last)S.last=simulate({});let stocks=S.model.nodes.filter(n=>n.type==='stock');E.behaviour.innerHTML=stocks.map(n=>{let a=S.last.series[n.symbol],start=a[0],end=a.at(-1),pct=start?((end-start)/start)*100:0;return `<div class="insight"><strong>${esc(n.name)} : ${pct>=0?'hausse':'baisse'} de ${Math.abs(pct).toFixed(0)} %</strong><small>De ${fmt(start)} à ${fmt(end)} sur ${S.model.simulation.horizon} ${esc(S.model.simulation.unit)}.</small></div>`}).join('');let checks=[['Structure',S.model.nodes.some(n=>n.type==='stock'),'Au moins un stock'],['Dynamique',S.model.nodes.some(n=>n.type==='flow'),'Au moins un flux'],['Hypothèses',S.model.nodes.some(n=>n.type==='parameter'),'Paramètres testables'],['Scénarios',S.model.scenarios.length>1,'Plusieurs futurs comparables'],['Boucles',loops.length>0,'Au moins une rétroaction'],['Formules',S.model.nodes.filter(n=>['flow','variable'].includes(n.type)).every(n=>n.formula),'Formules renseignées']];E.quality.innerHTML=checks.map(c=>`<div class="quality-item ${c[1]?'ok':'warn'}"><strong>${c[1]?'✓':'!'} ${c[0]}</strong><small>${c[2]}</small></div>`).join('')}
function findLoops(){let adj={};S.model.edges.forEach(e=>(adj[e.from]||=[]).push(e));let found=[],seen=new Set();S.model.nodes.forEach(start=>dfs(start.id,start.id,[],1,new Set()));function dfs(cur,target,path,sign,vis){if(path.length>7)return;for(let e of adj[cur]||[]){let ns=sign*(e.polarity==='-'?-1:1);if(e.to===target&&path.length>=1){let nodes=[target,...path.map(x=>x.to)],key=[...new Set(nodes)].sort().join('|');if(!seen.has(key)){seen.add(key);found.push({nodes:[target,...path.map(x=>x.to)],sign:ns})}}else if(!vis.has(e.to)){let nv=new Set(vis);nv.add(e.to);dfs(e.to,target,[...path,e],ns,nv)}}}return found}
function save(){localStorage.setItem('dynamic_canvas_v2',JSON.stringify(S.model))}function load(){try{return JSON.parse(localStorage.getItem('dynamic_canvas_v2'))}catch{return null}}
function exportModel(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S.model,null,2)],{type:'application/json'}));a.download='dynamic-canvas-model.json';a.click();URL.revokeObjectURL(a.href)}
function node(id){return S.model.nodes.find(n=>n.id===id)}function uid(p){return p+'_'+Math.random().toString(36).slice(2,9)}function slug(s=''){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'value'}function unique(b,ignore){let used=new Set(S.model?.nodes.filter(n=>n.id!==ignore).map(n=>n.symbol)||[]),s=b,i=2;while(used.has(s))s=b+'_'+i++;return s}function fmt(v){if(!Number.isFinite(+v))return '—';return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(+v)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(s){return esc(s)}let tt;function toast(s){clearTimeout(tt);E.toast.textContent=s;E.toast.classList.add('show');tt=setTimeout(()=>E.toast.classList.remove('show'),2200)}
})();